# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55a6062f245076f51654a65839944fbe"
name = "Sectify - AI Theme Builder"
handle = "sectify-ai-theme-builder"
<<<<<<< HEAD
application_url = "https://ids-participants-confidence-pe.trycloudflare.com"
=======
application_url = "https://way-customers-chemistry-meanwhile.trycloudflare.com"
>>>>>>> 509b2313b9471035f662809febcacc33d7979c0a
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  uri = "/webhooks/customers/data_request"
  compliance_topics = [ "customers/data_request" ]


   [[webhooks.subscriptions]]
  uri = "/webhooks/customers/redact"
  compliance_topics = [ "customers/redact" ]


  [[webhooks.subscriptions]]
  uri = "/webhooks/shop/redact"
  compliance_topics = [ "shop/redact" ]


[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
<<<<<<< HEAD
redirect_urls = ["https://ids-participants-confidence-pe.trycloudflare.com/auth/callback", "https://ids-participants-confidence-pe.trycloudflare.com/auth/shopify/callback", "https://ids-participants-confidence-pe.trycloudflare.com/api/auth/callback"]
=======
redirect_urls = ["https://way-customers-chemistry-meanwhile.trycloudflare.com/auth/callback", "https://way-customers-chemistry-meanwhile.trycloudflare.com/auth/shopify/callback", "https://way-customers-chemistry-meanwhile.trycloudflare.com/api/auth/callback"]
>>>>>>> 509b2313b9471035f662809febcacc33d7979c0a

[pos]
embedded = false
