# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "55a6062f245076f51654a65839944fbe"
name = "Section-store"
handle = "section-store-18"
application_url = "https://laser-agreements-domains-which.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_themes,write_themes"

[auth]
redirect_urls = ["https://laser-agreements-domains-which.trycloudflare.com/auth/callback", "https://laser-agreements-domains-which.trycloudflare.com/auth/shopify/callback", "https://laser-agreements-domains-which.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
